### PR TITLE
Added support for subtitles encoding with the Iconv library.

### LINKED ISSUE #68: Subs showing wrong (encoding issue)
Hi, 
I tried lots of movies and some symbols with accent like à, è, etc... are show with a big "?" instead.
You can try on Gone Girl with french subs, the right beginning of the movie is showing it easily

### PR DESCRIPTION
**Pull request by shali3**
This should fix #68

### CODE REVIEW

**Comment by meo-in-silent-hill** [comment]
did not work with the arabic subtitle :(
you see with Suits season5 the arabic subtilte works great but the other tvShows or movies are not working still symbols.

great app though

**Comment by shali3** [comment]
I just tested it with the movie Interstellar and It's working great. Please provide a movie / Episode that this is *not* working for you

**Comment by OstlerDev** [comment]
Testing this to merge right now.

**Comment by shali3** [comment]
Cool :+1:

**Comment by Samb00** [comment]
Working very well with Arabic Subtitle Thank you so much guys you are AMAZING
wish you can add preferred subtitle option that will be so cool also

**Comment by OstlerDev** [comment]
Glad that it works for you! All the thanks for this fix goes to @shali3 . He did an amazing job in finding and implementing a fix.

**Comment by diogosmiranda** [comment]
OstlerDev
I would like to fix this error in PORTUGUESE-BRAZIL subtitle? Thanks for everything
img_1504

**Comment by Samb00** [comment]
@diogosmiranda @OstlerDev i have same error with the Arabic subtitle in some movies

**Comment by diogosmiranda** [comment]
I'm with these problems in all the movies and tv shows

**Comment by OstlerDev** [comment]
@Samb00 @diogosmiranda Can you either post a full debug log (https://github.com/OstlerDev/PopcornTV/wiki/How-to-report-an-issue) or state the show, episode, and subtitle you chose?

Please keep in mind that by posting the debug log I will be able to fix it much sooner as I do not have to reproduce the issue on my end, but can rather look at the debug log to see the issue.

**Comment by Samb00** [comment]
I will do that tonight.

**Comment by OstlerDev** [comment]
@Samb00 Thanks.

**Comment by Samb00** [comment]
@OstlerDev Here you go my Friend The LOG
http://pastebin.com/3hHN4AFT

**Pull request merged**
